### ISSUE TITLE
Image browser not working

### ISSUE THREAD

**Issue by simonelmundo** [sheldonchiu/AI-AIO#24]
It never worked for me , here is the log: 

### Command received ###
[2023-09-25 11:27:06] Starting Image Browser
### Setting up Image Browser ###
[2023-09-25 11:27:06] Setting up Image Browser
[2023-09-25 11:27:06] Updating Repo /storage/sd-webui-infinite-image-browsing ...
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
   git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
    git branch --set-upstream-to=origin/<branch> master
### ERROR ###

Error
Not running
cat: /tmp/image_browser.pid: No such file or directory
/bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]

**Comment by sheldonchiu** [comment]
Is now fixed, please run `cd /notebooks && git pull && cd image_browser && bash control.sh reload` to update

**Comment by simonelmundo** [comment]
Is there another way to open the image browser other than your website? maybe a command in the terminal? 

I updated it like you said but the website https://ai.sheldonxxxx.cc/ still didn't work, so I reloaded the page but then it lost connection with my notebook .

**Comment by sheldonchiu** [comment]
> Do I have to open the image browser through your website? Is there a way to do it from the terminal with a command?

You can either run `status` in terminal, and it will print all the website url, or receive using discord.

> When I refreshed the page, it disconnected from my notebook.

In this case, you need to either import the perviously exported setting or enter the api key and environment Name, then click the sync button to reconnect to the notebook.
  
![Screenshot 2023-09-26 at 9 27 15 PM](https://github.com/sheldonchiu/AI-AIO/assets/32926567/1738979e-987c-430d-b465-4711b68246e6)

**Comment by simonelmundo** [comment]
Should image browser be working now? I still can't get it to work  "Error Encountered error while start image_browser."
I get the same error as before

**Comment by sheldonchiu** [comment]
oh, you need to run `rm -rf /storage/sd-webui-infinite-image-browsing` to clean up, then run `cd /notebooks && git pull && cd image_browser && bash control.sh reload` to start image browser.

Next time you should be able to start image browser normally.

**Comment by simonelmundo** [comment]
IT WORK !!! 
Thanks man!
